In [1]:
import numpy as np

In [2]:
arr_1 = [1,2,3,4,5,6]
arr_1 += 1

TypeError: 'int' object is not iterable

In [3]:
arr_2 = np.array([1,2,3,4,5,6])
print (type(arr_2))

<class 'numpy.ndarray'>


In [4]:
arr_2 += 1

In [5]:
arr_2

array([2, 3, 4, 5, 6, 7])

In [6]:
arr_3 = arr_2 + 1
arr_3

array([3, 4, 5, 6, 7, 8])

In [7]:
arr_3 + arr_2

array([ 5,  7,  9, 11, 13, 15])

In [8]:
arr_2 * arr_3

array([ 6, 12, 20, 30, 42, 56])

In [9]:
arr_2 [0]

2

In [10]:
arr_2 [1:]

array([3, 4, 5, 6, 7])

In [11]:
arr_2.shape

(6,)

In [12]:
np.array([[1,2,3],["a","b","c"]])

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U11')