In [1]:
import numpy as np

m_1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
m_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
m_2 = m_1
m_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
m_2[1,2] = 600
m_2

array([[  1,   2,   3],
       [  4,   5, 600],
       [  7,   8,   9]])

In [4]:
m_1

array([[  1,   2,   3],
       [  4,   5, 600],
       [  7,   8,   9]])

In [5]:
m_1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
m_3 = m_1.copy()
m_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
m_3[1,2] = 600
m_3

array([[  1,   2,   3],
       [  4,   5, 600],
       [  7,   8,   9]])

In [7]:
m_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
m_4 = np.arange(0,100,20)
m_4

array([ 0, 20, 40, 60, 80])

In [9]:
m_5 = np.random.rand(10)
m_5

array([0.73036823, 0.37487132, 0.15838986, 0.98247093, 0.9371652 ,
       0.33477123, 0.99400497, 0.52146428, 0.25057253, 0.23720177])