In [1]:
import numpy as np

arr_1 = np.array([[5.5,1.1,8.7],
                 [4.5,9.8,0.9]])
arr_1

array([[5.5, 1.1, 8.7],
       [4.5, 9.8, 0.9]])

In [2]:
np.sort(arr_1)

array([[1.1, 5.5, 8.7],
       [0.9, 4.5, 9.8]])

In [3]:
arr_1

array([[5.5, 1.1, 8.7],
       [4.5, 9.8, 0.9]])

In [4]:
np.argsort(arr_1)

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [5]:
arr_2 = np.arange(0,10)

In [6]:
arr_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr_3 = np.array([3.4,6.7,7.8])
np.searchsorted(arr_2, arr_3)

array([4, 7, 8], dtype=int64)