In [1]:
import numpy as np

In [2]:
arr_1 = np.array([1,2,3,4,5,6])
arr_1

array([1, 2, 3, 4, 5, 6])

In [5]:
np.savetxt("np_test4.txt", arr_1, fmt="%.2f")

In [6]:
arr_2 = np.array([1,2,3,4,5,6])
arr_2

array([1, 2, 3, 4, 5, 6])

In [7]:
np.save("np_test5.npy", arr_2)

In [8]:
arr_3 = np.load("np_test5.npy")
arr_3

array([1, 2, 3, 4, 5, 6])

In [9]:
arr_4 = np.arange(100)
arr_4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
np.savez("np_test6.npz", a=arr_3, b=arr_4)

In [11]:
dict_1 = np.load("np_test6.npz")

In [12]:
dict_1.keys()

['a', 'b']

In [13]:
dict_1["a"]

array([1, 2, 3, 4, 5, 6])

In [14]:
dict_1["b"]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])